FROM node:22-alpine

WORKDIR /usr/src/app

ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 5173 3000

CMD ["npm", "run", "dev"]
