# Use the official Node.js image
FROM node:16

ARG FRONTEND_PORT

RUN mkdir -p server
WORKDIR /server

COPY package.json package-lock.json ./
RUN npm install

COPY . .
RUN npm run build

EXPOSE $FRONTEND_PORT

# Command to run the application
CMD ["npm", "run", "start"]
